version: "3.8"

services:
  cloudflaretinyurl:
    build: .
    container_name: cloudflaretinyurl_service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgres://cloudflare_user:Cf!Db@8#Xy2&9z@postgres:5432/cloudflaretinyurl?sslmode=disable"
      REDIS_URL: "redis:6379"
    restart: always

  postgres:
    image: postgres:13
    container_name: cloudflaretinyurl_postgres
    environment:
      POSTGRES_USER: cloudflare_user
      POSTGRES_PASSWORD: Cf!Db@8#Xy2&9z
      POSTGRES_DB: cloudflaretinyurl
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # Create Tables on start

  redis:
    image: redis:6.2
    container_name: cloudflaretinyurl_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"] # Enables AOF persistence

volumes:
  pgdata:
  redisdata:
